services:
  web:
    build: fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/app
    networks:
      - ollama-net
  ollama:
    build: ollama
    ports:
      - 11434:11434 
    volumes:
      - ./ollama:/app
    networks:
      - ollama-net
    entrypoint: ["/usr/bin/bash", "pull-llama3.sh"]

networks:
  ollama-net:
    driver: bridge